version: "3.1"
services:
  pytorch:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "10000:8888"
      - "10001:8080"
      - "10002:22"
      - "10003:20"
      - "10004:21"
    volumes:
      - TES-2023:/workspace
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
volumes:
  TES-2023:
    external: true

